name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - jupyterlab=3.6.3
  - seaborn=0.12.2
  - pandas=2.1.1
  - pip=23.3
  - pandas-profiling=2.9.0
  - pyarrow=11.0.0
  - wandb=0.15.12
  - pip:
      - wandb==0.10.31