name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - ipython=8.15.0
  - notebook=6.5.4
  - jupyterlab=3.6.3
  - cookiecutter=1.7.3
  - matplotlib=3.7.2
  - pandas=2.1.1
  - git=2.40.1
  - hydra-core=1.3.2
  - pip=23.3
  - pyarrow=11.0.0
  - requests=2.31.0
  - pip:
      - wandb==0.15.2
      - mlflow==2.7.1
