name: test_regression_model
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas=2.1.1
  - pip=23.3
  - wandb=0.15.12
  - scikit-learn=1.3.0
  - pip:
      - mlflow==2.7.1     
      - git+https://github.com/alfreedolf/build-ml-pipeline-for-short-term-rental-prices.git#egg=wandb-utils&subdirectory=components
