name: basic_cleaning
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas=2.1.1
  - pip=23.3
  - scikit-learn=1.3.0
  - matplotlib=3.7.2
  - pillow=9.4.0
  - wandb=0.15.12
  - pip:
      - mlflow==2.7.1
